name: inssurancustomer
description: App for insurance customer

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.5
  flutter_screenutil: ^5.5.4
  flutter_easyloading: ^3.0.3
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  get: ^4.6.5
  shared_preferences: ^2.0.15
  flutter_remix: ^0.0.3
  email_validator: ^2.1.17
  http: ^0.13.4
  cached_network_image: ^3.2.2
  flutter_lints: ^2.0.0
  preload_page_view: ^0.1.6
  url_launcher: ^6.0.18
  flutter_phone_direct_caller: ^2.1.1
  pin_code_fields: ^7.4.0
  syncfusion_flutter_pdfviewer: 21.1.39
  syncfusion_localizations: 21.1.39

flutter:
  uses-material-design: true

  fonts:
    - family: AvenirHeavy
      fonts:
        - asset: assets/fonts/AvenirHeavy.ttf
    - family: AvenirRoman
      fonts:
        - asset: assets/fonts/AvenirRoman.ttf
    - family: GilroyLight
      fonts:
        - asset: assets/fonts/GilroyLight.ttf

  assets:
    - assets/images/login.svg
    - assets/images/logo.svg

